{
    'name': 'Pengajuan Asesi & Pendaftaran Siswa LSP',
    'version': '1.0.0',
    'summary': 'Module untuk Pengajuan Asesi dan Portal Pendaftaran Siswa LSP',
    'description': 'Modul lengkap untuk system manajemen LSP dengan fitur pendaftaran siswa melalui portal website custom',
    'category': 'Tools',
    'author': 'You',
    'website': '',
    'license': 'LGPL-3',
    'depends': ['base', 'portal'],
    'data': [
        'security/ir.model.access.csv',
        'security/student_document_security.xml',
        'views/asesi_views.xml',
        'views/lsp_student_document_views.xml',
        'views/lsp_student_inherit_views.xml',
        'wizard/lsp_student_verify_wizard_views.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
